# Generated by Django 4.2.16 on 2026-09-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='monthlyattendancesummary',
            options={'ordering': ['-year', '-month']},
        ),
    ]
