# Generated by Django 4.2.16 on 2026-07-10 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('quran', 'Quran Recitation'), ('quran_memorization', 'Quran Memorization'), ('tajweed', 'Tajweed Rules'), ('ai', 'Artificial Intelligence'), ('blockchain', 'Blockchain Basics'), ('programming', 'Programming for Kids'), ('web_dev', 'Web Development')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('price_per_month', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('duration_minutes', models.IntegerField(default=45)),
                ('classes_per_week', models.IntegerField(default=3)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('syllabus', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
