# Generated by Django 4.2.16 on 2026-07-10 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('student_age', models.IntegerField()),
                ('student_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_whatsapp', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('preferred_days', models.CharField(choices=[('mon_wed_fri', 'Monday, Wednesday, Friday'), ('tue_thu_sat', 'Tuesday, Thursday, Saturday'), ('weekends', 'Weekends Only'), ('custom', 'Custom Schedule')], default='mon_wed_fri', max_length=20)),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (7-11 AM)'), ('afternoon', 'Afternoon (12-4 PM)'), ('evening', 'Evening (5-9 PM)')], default='evening', max_length=10)),
                ('preferred_timezone', models.CharField(default='UTC', max_length=50)),
                ('special_requests', models.TextField(blank=True)),
                ('current_quran_level', models.CharField(blank=True, max_length=50)),
                ('knows_arabic', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting_payment', 'Waiting for Payment'), ('active', 'Active Student'), ('completed', 'Course Completed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('assigned_time_slot', models.CharField(blank=True, max_length=50)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
