# Generated by Django 4.2.16 on 2026-09-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['teacher', 'start_time'], name='scheduling__teacher_b6157e_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['student', 'start_time'], name='scheduling__student_b461f8_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['status', 'start_time'], name='scheduling__status_aea94c_idx'),
        ),
    ]
